version: '2.2'

services: 
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - 8000:8000
      - 4505:4505
  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    depends_on:
      - salt-master
    scale: 2
